USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=aja_behavorial_wireless_network
#PACKAGE_NAME=teacher_wireless_network
#PACKAGE_NAME=cats2_wireless_network
PACKAGE_NAME=aja_behavorial_wireless_network
REVERSE_DOMAIN=com.emoxter
PAYLOAD=\
	pack-script-postinstall
