#!/bin/bash

ssid=""

#possible values here are OPEN, WPA, WPAE (WPA Enterprise), WPA2, WPAE2, WEP or 8021XWEP
securitytype="WPA2"

password=""


device=$(networksetup -listallhardwareports | grep -E '(Wi-Fi|AirPort)' -A 1 | grep -o en.)

if [ $device != "" ] 
	then
	sudo /usr/sbin/networksetup -addpreferredwirelessnetworkatindex $device $ssid 0 $securitytype $password
        sudo /usr/sbin/networksetup -setairportnetwork $device $ssid $password
fi

exit 0
