USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make

TITLE=nacs-firstboot-yosemite
PACKAGE_NAME=${TITLE}
REVERSE_DOMAIN=org.nacswildcats
PACKAGE_VERSION=2.0
PAYLOAD=\
	pack-script-postinstall 
